(RE-13966) Minor changes for style and consistency

diff --git a/ci/stage_and_ship b/ci/stage_and_ship
--- a/ci/stage_and_ship
+++ b/ci/stage_and_ship
@@ -26,7 +26,7 @@ export BUNDLE_BIN=.bundle/bin
 
 bundle install
 
-if [ $NIGHTLY == 'true' ]; then
+if [ $NIGHTLY == true ]; then
   bundle exec rake pl:jenkins:stage_nightly_release_packages --trace
   bundle exec rake pl:remote:update_nightly_repos --trace
   bundle exec rake pl:remote:deploy_nightlies_to_s3 --trace
@@ -35,3 +35,20 @@ else
   bundle exec rake pl:remote:update_yum_repo pl:remote:update_apt_repo --trace
   bundle exec rake pl:remote:deploy_final_builds_to_s3 pl:remote:deploy_to_rsync_server --trace
 fi
+
+case $NIGHTLY in
+  true)
+    bundle exec rake pl:jenkins:stage_nightly_release_packages --trace
+    bundle exec rake pl:remote:update_nightly_repos --trace
+    bundle exec rake pl:remote:deploy_nightlies_to_s3 --trace
+  ;;
+  false)
+    bundle exec rake pl:jenkins:stage_release_packages --trace
+    bundle exec rake pl:remote:update_yum_repo pl:remote:update_apt_repo --trace
+    bundle exec rake pl:remote:deploy_final_builds_to_s3 pl:remote:deploy_to_rsync_server --trace
+  ;;
+  *)
+    echo 'Error: Unrecognized value for $NIGHTLY: ' $NIGHTLY 1>&2
+    exit 1
+  ;;
+esac
